-- ============================================================================
-- E2E seed for the core database (consistent v24 schema + deterministic data).
--
-- Generated by applying servers/core/db/migration/*.up.sql to an empty Postgres
-- (so schema_migrations=24 and the server's startup 'migrate up' is a no-op),
-- then inserting a few courses, students, and course-phase types.
-- See e2e/README.md ('Test data') to regenerate.
-- ============================================================================
--
-- PostgreSQL database dump
--

\restrict uiXVLaqKXF7gSedZuy9c3H2gUqZa6VyxWQoZSShJpDmfp6Ju8Xhj14PSv45Sbb5

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: course_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.course_type AS ENUM (
    'lecture',
    'seminar',
    'practical course'
);


--
-- Name: export_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.export_status AS ENUM (
    'pending',
    'complete',
    'failed',
    'no_data',
    'archived'
);


--
-- Name: gender; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.gender AS ENUM (
    'male',
    'female',
    'diverse',
    'prefer_not_to_say'
);


--
-- Name: note_tag_color; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.note_tag_color AS ENUM (
    'blue',
    'green',
    'red',
    'yellow',
    'orange',
    'pink'
);


--
-- Name: pass_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.pass_status AS ENUM (
    'passed',
    'failed',
    'not_assessed'
);


--
-- Name: study_degree; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.study_degree AS ENUM (
    'bachelor',
    'master'
);


--
-- Name: update_files_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_files_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


--
-- Name: update_last_modified_column(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_last_modified_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.last_modified = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: application_answer_file_upload; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_answer_file_upload (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    application_question_id uuid NOT NULL,
    course_participation_id uuid NOT NULL,
    file_id uuid NOT NULL
);


--
-- Name: application_answer_multi_select; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_answer_multi_select (
    id uuid NOT NULL,
    application_question_id uuid NOT NULL,
    answer text[],
    course_participation_id uuid NOT NULL
);


--
-- Name: application_answer_text; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_answer_text (
    id uuid NOT NULL,
    application_question_id uuid NOT NULL,
    answer text,
    course_participation_id uuid NOT NULL
);


--
-- Name: application_assessment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_assessment (
    id uuid NOT NULL,
    score integer,
    course_phase_id uuid NOT NULL,
    course_participation_id uuid NOT NULL
);


--
-- Name: application_question_file_upload; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_question_file_upload (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    course_phase_id uuid NOT NULL,
    title text NOT NULL,
    description text,
    is_required boolean DEFAULT false NOT NULL,
    allowed_file_types text,
    max_file_size_mb integer,
    order_num integer NOT NULL,
    accessible_for_other_phases boolean DEFAULT false NOT NULL,
    access_key text
);


--
-- Name: application_question_multi_select; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_question_multi_select (
    id uuid NOT NULL,
    course_phase_id uuid NOT NULL,
    title text,
    description text,
    placeholder text,
    error_message text,
    is_required boolean,
    min_select integer,
    max_select integer,
    options text[],
    order_num integer,
    accessible_for_other_phases boolean DEFAULT false,
    access_key character varying(50) DEFAULT ''::character varying
);


--
-- Name: application_question_text; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_question_text (
    id uuid NOT NULL,
    course_phase_id uuid NOT NULL,
    title text,
    description text,
    placeholder text,
    validation_regex text,
    error_message text,
    is_required boolean,
    allowed_length integer,
    order_num integer,
    accessible_for_other_phases boolean DEFAULT false,
    access_key character varying(50) DEFAULT ''::character varying
);


--
-- Name: course; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course (
    id uuid NOT NULL,
    name text NOT NULL,
    start_date date,
    end_date date,
    semester_tag text,
    course_type public.course_type NOT NULL,
    ects integer,
    restricted_data jsonb,
    student_readable_data jsonb DEFAULT '{}'::jsonb,
    template boolean DEFAULT false NOT NULL,
    short_description character varying(255),
    long_description text,
    archived boolean DEFAULT false NOT NULL,
    archived_on timestamp with time zone,
    CONSTRAINT check_end_date_after_start_date CHECK (((template = true) OR (end_date > start_date)))
);


--
-- Name: course_participation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_participation (
    id uuid NOT NULL,
    course_id uuid NOT NULL,
    student_id uuid NOT NULL
);


--
-- Name: course_phase; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_phase (
    id uuid NOT NULL,
    course_id uuid NOT NULL,
    name text,
    restricted_data jsonb,
    is_initial_phase boolean NOT NULL,
    course_phase_type_id uuid NOT NULL,
    student_readable_data jsonb DEFAULT '{}'::jsonb
);


--
-- Name: course_phase_graph; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_phase_graph (
    from_course_phase_id uuid NOT NULL,
    to_course_phase_id uuid NOT NULL
);


--
-- Name: course_phase_participation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_phase_participation (
    course_participation_id uuid NOT NULL,
    course_phase_id uuid NOT NULL,
    restricted_data jsonb,
    pass_status public.pass_status DEFAULT 'not_assessed'::public.pass_status,
    last_modified timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    student_readable_data jsonb DEFAULT '{}'::jsonb
);


--
-- Name: course_phase_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_phase_type (
    id uuid NOT NULL,
    name text NOT NULL,
    initial_phase boolean DEFAULT false NOT NULL,
    base_url text DEFAULT 'core'::text NOT NULL,
    description text
);


--
-- Name: course_phase_type_participation_provided_output_dto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_phase_type_participation_provided_output_dto (
    id uuid NOT NULL,
    course_phase_type_id uuid NOT NULL,
    dto_name text NOT NULL,
    version_number integer NOT NULL,
    endpoint_path text NOT NULL,
    specification jsonb NOT NULL
);


--
-- Name: course_phase_type_participation_required_input_dto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_phase_type_participation_required_input_dto (
    id uuid NOT NULL,
    course_phase_type_id uuid NOT NULL,
    dto_name text NOT NULL,
    specification jsonb NOT NULL
);


--
-- Name: course_phase_type_phase_provided_output_dto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_phase_type_phase_provided_output_dto (
    id uuid NOT NULL,
    course_phase_type_id uuid NOT NULL,
    dto_name text NOT NULL,
    version_number integer NOT NULL,
    endpoint_path text NOT NULL,
    specification jsonb NOT NULL
);


--
-- Name: course_phase_type_phase_required_input_dto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_phase_type_phase_required_input_dto (
    id uuid NOT NULL,
    course_phase_type_id uuid NOT NULL,
    dto_name text NOT NULL,
    specification jsonb NOT NULL
);


--
-- Name: files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.files (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    filename character varying(500) NOT NULL,
    original_filename character varying(500) NOT NULL,
    content_type character varying(200) NOT NULL,
    size_bytes bigint NOT NULL,
    storage_key character varying(500) NOT NULL,
    storage_provider character varying(50) DEFAULT 'seaweedfs'::character varying NOT NULL,
    uploaded_by_user_id character varying(200) NOT NULL,
    uploaded_by_email character varying(200),
    course_phase_id uuid,
    description text,
    tags character varying(100)[],
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    CONSTRAINT files_size_bytes_check CHECK ((size_bytes >= 0))
);


--
-- Name: note; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.note (
    id uuid NOT NULL,
    for_student uuid NOT NULL,
    author uuid NOT NULL,
    author_name text NOT NULL,
    author_email text NOT NULL,
    date_created timestamp with time zone DEFAULT now() NOT NULL,
    date_deleted timestamp with time zone,
    deleted_by uuid
);


--
-- Name: note_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.note_tag (
    id uuid NOT NULL,
    name text NOT NULL,
    color public.note_tag_color NOT NULL
);


--
-- Name: note_tag_relation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.note_tag_relation (
    note_id uuid NOT NULL,
    tag_id uuid NOT NULL
);


--
-- Name: note_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.note_version (
    id uuid NOT NULL,
    content text NOT NULL,
    date_created timestamp with time zone DEFAULT now() NOT NULL,
    version_number integer NOT NULL,
    for_note uuid NOT NULL
);


--
-- Name: note_with_versions; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.note_with_versions AS
SELECT
    NULL::uuid AS id,
    NULL::uuid AS author,
    NULL::text AS author_name,
    NULL::text AS author_email,
    NULL::uuid AS for_student,
    NULL::timestamp with time zone AS date_created,
    NULL::timestamp with time zone AS date_deleted,
    NULL::uuid AS deleted_by,
    NULL::jsonb AS versions,
    NULL::jsonb AS tags;


--
-- Name: participation_data_dependency_graph; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.participation_data_dependency_graph (
    from_course_phase_id uuid NOT NULL,
    to_course_phase_id uuid NOT NULL,
    from_course_phase_dto_id uuid NOT NULL,
    to_course_phase_dto_id uuid NOT NULL
);


--
-- Name: phase_data_dependency_graph; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.phase_data_dependency_graph (
    from_course_phase_id uuid NOT NULL,
    to_course_phase_id uuid NOT NULL,
    from_course_phase_dto_id uuid NOT NULL,
    to_course_phase_dto_id uuid NOT NULL
);


--
-- Name: privacy_export; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.privacy_export (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    student_id uuid,
    status public.export_status DEFAULT 'pending'::public.export_status NOT NULL,
    date_created timestamp with time zone DEFAULT now() NOT NULL,
    valid_until timestamp with time zone NOT NULL,
    next_request_allowed_at timestamp with time zone NOT NULL
);


--
-- Name: privacy_export_document; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.privacy_export_document (
    id uuid NOT NULL,
    export_id uuid,
    date_created timestamp with time zone DEFAULT now() NOT NULL,
    source_name text NOT NULL,
    object_key text NOT NULL,
    status public.export_status DEFAULT 'pending'::public.export_status NOT NULL,
    file_size bigint,
    downloaded_at timestamp with time zone
);


--
-- Name: privacy_export_with_docs; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.privacy_export_with_docs AS
SELECT
    NULL::uuid AS id,
    NULL::uuid AS user_id,
    NULL::uuid AS student_id,
    NULL::public.export_status AS status,
    NULL::timestamp with time zone AS date_created,
    NULL::timestamp with time zone AS valid_until,
    NULL::timestamp with time zone AS next_request_allowed_at,
    NULL::jsonb AS documents;


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version bigint NOT NULL,
    dirty boolean NOT NULL
);


--
-- Name: student; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student (
    id uuid NOT NULL,
    first_name character varying(50),
    last_name character varying(50),
    email character varying(255),
    matriculation_number character varying(30),
    university_login character varying(20),
    has_university_account boolean,
    gender public.gender NOT NULL,
    nationality character varying(2),
    study_program character varying(100),
    study_degree public.study_degree DEFAULT 'bachelor'::public.study_degree NOT NULL,
    current_semester integer,
    last_modified timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Data for Name: application_answer_file_upload; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: application_answer_multi_select; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: application_answer_text; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: application_assessment; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: application_question_file_upload; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.application_question_file_upload VALUES ('bbbb0001-0000-0000-0000-0000000000b1', 'aaaa1111-0000-0000-0000-0000000000a1', 'Upload your CV', 'Attach your CV.', false, '.txt,.pdf', 50, 0, false, NULL);


--
-- Data for Name: application_question_multi_select; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: application_question_text; Type: TABLE DATA; Schema: public; Owner: -
--

-- Required text question on the iPraktikumFull Application phase, so the
-- application journey exercises the configurable form (answersText round-trip).
INSERT INTO public.application_question_text VALUES ('ab000001-0000-0000-0000-000000000001', 'd0000001-0000-0000-0000-000000000001', 'Motivation', 'Why do you want to join this course?', 'Your motivation', '', '', true, 500, 1, false, '');


--
-- Data for Name: course; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.course VALUES ('d7307be2-d3dc-496e-86f0-643bff6cc1c8', 'iPraktikum', '2024-10-13', '2025-02-14', 'ios2425', 'practical course', 10, '{"icon": "graduation-cap", "bg-color": "bg-blue-100"}', '{"icon": "graduation-cap", "bg-color": "bg-blue-100"}', false, 'iOS practical course', 'The iPraktikum is a hands-on iOS development course.', false, NULL);
INSERT INTO public.course VALUES ('e12ffe63-448d-4469-a840-1699e9b328d1', 'iPraktikum-Test', '2024-12-15', '2025-03-15', 'ios2425', 'practical course', 10, '{"icon": "graduation-cap", "bg-color": "bg-green-100"}', '{"icon": "graduation-cap", "bg-color": "bg-green-100"}', false, 'Test variant', 'A test course.', false, NULL);
INSERT INTO public.course VALUES ('be780b32-a678-4b79-ae1c-80071771d254', 'TestCourse', '2024-12-19', '2025-04-19', 'ios2425', 'seminar', 5, '{"icon": "book", "bg-color": "bg-purple-100"}', '{"icon": "book", "bg-color": "bg-purple-100"}', false, 'Seminar course', 'A seminar.', false, NULL);
INSERT INTO public.course VALUES ('c0000001-0000-0000-0000-000000000001', 'iPraktikumFull', '2025-04-01', '2025-09-30', 'ios2425', 'practical course', 10, '{"icon": "graduation-cap", "bg-color": "bg-blue-100"}', '{"icon": "graduation-cap", "bg-color": "bg-blue-100"}', false, 'Full-cycle practical course', 'A practical course spanning application, interview, matching, team allocation, and assessment. Seeded with participations and course-scoped roles for e2e.', false, NULL);


--
-- Data for Name: course_participation; Type: TABLE DATA; Schema: public; Owner: -
--

-- The Keycloak e2e users `student` / `student2` enrolled in iPraktikum
-- (matched to the student rows below via matriculation_number/university_login
-- token claims). Neither is enrolled in TestCourse — its self team allocation
-- phase is the negative-auth fixture.
INSERT INTO public.course_participation VALUES ('ca000005-0000-4000-8000-000000000005', 'd7307be2-d3dc-496e-86f0-643bff6cc1c8', 'e0000005-0000-0000-0000-000000000005');
INSERT INTO public.course_participation VALUES ('ca000007-0000-4000-8000-000000000007', 'd7307be2-d3dc-496e-86f0-643bff6cc1c8', 'a5000007-0000-4000-8000-000000000007');
-- iPraktikumFull participations. a0000001 is the same Keycloak `student` user (Stan,
-- 00000005/no42tum) that the iPraktikum self team allocation fixtures above use.
-- ca000008 enrolls `student2` (Selma) too, so assessment visibility tests have a
-- second in-course student.
INSERT INTO public.course_participation VALUES ('a0000001-0000-0000-0000-000000000001', 'c0000001-0000-0000-0000-000000000001', 'e0000005-0000-0000-0000-000000000005');
INSERT INTO public.course_participation VALUES ('ca000008-0000-4000-8000-000000000008', 'c0000001-0000-0000-0000-000000000001', 'a5000007-0000-4000-8000-000000000007');
INSERT INTO public.course_participation VALUES ('a0000002-0000-0000-0000-000000000002', 'c0000001-0000-0000-0000-000000000001', '3869f209-9a21-4595-ae0e-bc6d6a3e2d63');
INSERT INTO public.course_participation VALUES ('a0000003-0000-0000-0000-000000000003', 'c0000001-0000-0000-0000-000000000001', '5eb545c2-c2eb-4c77-9c0f-46ccf7c45d07');
INSERT INTO public.course_participation VALUES ('a0000004-0000-0000-0000-000000000004', 'c0000001-0000-0000-0000-000000000001', '2428d311-4ad4-4d91-a46e-e5e2a5a4a3ee');
INSERT INTO public.course_participation VALUES ('a0000005-0000-0000-0000-000000000005', 'c0000001-0000-0000-0000-000000000001', '23bf3123-4f0d-473c-9ef5-d0333e29fe9a');
INSERT INTO public.course_participation VALUES ('a0000006-0000-0000-0000-000000000006', 'c0000001-0000-0000-0000-000000000001', '777286f4-a3e7-4bcd-bf57-13d178bf582d');



--
-- Data for Name: course_phase; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: course_phase_graph; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.course_phase_graph VALUES ('aaaa1111-0000-0000-0000-0000000000a1', 'aaaa2222-0000-0000-0000-0000000000a2');
INSERT INTO public.course_phase_graph VALUES ('d0000001-0000-0000-0000-000000000001', 'd0000002-0000-0000-0000-000000000002');
INSERT INTO public.course_phase_graph VALUES ('d0000002-0000-0000-0000-000000000002', 'd0000003-0000-0000-0000-000000000003');
INSERT INTO public.course_phase_graph VALUES ('d0000003-0000-0000-0000-000000000003', 'd0000004-0000-0000-0000-000000000004');
INSERT INTO public.course_phase_graph VALUES ('d0000004-0000-0000-0000-000000000004', 'd0000005-0000-0000-0000-000000000005');
-- Certificate appended to the tail of the iPraktikumFull chain (after Assessment).
INSERT INTO public.course_phase_graph VALUES ('d0000005-0000-0000-0000-000000000005', 'd000000d-0000-0000-0000-00000000000d');



--
-- Data for Name: course_phase_participation; Type: TABLE DATA; Schema: public; Owner: -
--

-- Both e2e students participate in the iPraktikum self team allocation phase
-- (needed by the student UI's own-participation lookup and the lecturer
-- participants table; backend auth checks course-level enrollment).
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('ca000005-0000-4000-8000-000000000005', 'aaaa2222-0000-0000-0000-0000000000a2', '{}', 'passed', '{}');
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('ca000007-0000-4000-8000-000000000007', 'aaaa2222-0000-0000-0000-0000000000a2', '{}', 'passed', '{}');
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('ca000005-0000-4000-8000-000000000005', 'aaaa4444-0000-0000-0000-0000000000a4', '{}', 'passed', '{}');
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('ca000007-0000-4000-8000-000000000007', 'aaaa4444-0000-0000-0000-0000000000a4', '{}', 'passed', '{}');
-- Funnel across the iPraktikumFull graph. course_participation a0000001 (the seeded `student` user)
-- appears in every phase; the roster narrows toward Assessment.
INSERT INTO public.course_phase_participation VALUES ('a0000001-0000-0000-0000-000000000001', 'd0000001-0000-0000-0000-000000000001', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000002-0000-0000-0000-000000000002', 'd0000001-0000-0000-0000-000000000001', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000003-0000-0000-0000-000000000003', 'd0000001-0000-0000-0000-000000000001', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000004-0000-0000-0000-000000000004', 'd0000001-0000-0000-0000-000000000001', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000005-0000-0000-0000-000000000005', 'd0000001-0000-0000-0000-000000000001', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000006-0000-0000-0000-000000000006', 'd0000001-0000-0000-0000-000000000001', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000001-0000-0000-0000-000000000001', 'd0000002-0000-0000-0000-000000000002', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000002-0000-0000-0000-000000000002', 'd0000002-0000-0000-0000-000000000002', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000003-0000-0000-0000-000000000003', 'd0000002-0000-0000-0000-000000000002', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000004-0000-0000-0000-000000000004', 'd0000002-0000-0000-0000-000000000002', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000005-0000-0000-0000-000000000005', 'd0000002-0000-0000-0000-000000000002', '{}', 'passed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000001-0000-0000-0000-000000000001', 'd0000003-0000-0000-0000-000000000003', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000002-0000-0000-0000-000000000002', 'd0000003-0000-0000-0000-000000000003', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000003-0000-0000-0000-000000000003', 'd0000003-0000-0000-0000-000000000003', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000004-0000-0000-0000-000000000004', 'd0000003-0000-0000-0000-000000000003', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000001-0000-0000-0000-000000000001', 'd0000004-0000-0000-0000-000000000004', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000002-0000-0000-0000-000000000002', 'd0000004-0000-0000-0000-000000000004', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000003-0000-0000-0000-000000000003', 'd0000004-0000-0000-0000-000000000004', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000004-0000-0000-0000-000000000004', 'd0000004-0000-0000-0000-000000000004', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000001-0000-0000-0000-000000000001', 'd0000005-0000-0000-0000-000000000005', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000002-0000-0000-0000-000000000002', 'd0000005-0000-0000-0000-000000000005', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000003-0000-0000-0000-000000000003', 'd0000005-0000-0000-0000-000000000005', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
INSERT INTO public.course_phase_participation VALUES ('a0000004-0000-0000-0000-000000000004', 'd0000005-0000-0000-0000-000000000005', '{}', 'not_assessed', '2025-01-09 18:20:28.256593', '{}');
-- Standalone assessment fixture phases (see the course_phase inserts below):
-- Stan + Selma in the visibility phase, Stan in the self-evaluation phase,
-- Stan in the print phase.
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('a0000001-0000-0000-0000-000000000001', 'd0000006-0000-0000-0000-000000000006', '{}', 'not_assessed', '{}');
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('ca000008-0000-4000-8000-000000000008', 'd0000006-0000-0000-0000-000000000006', '{}', 'not_assessed', '{}');
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('a0000001-0000-0000-0000-000000000001', 'd0000007-0000-0000-0000-000000000007', '{}', 'not_assessed', '{}');
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('a0000001-0000-0000-0000-000000000001', 'd0000009-0000-0000-0000-000000000009', '{}', 'not_assessed', '{}');
-- Standalone matching re-import phase (see the course_phase insert below):
-- Stan + Selma participate, each carrying a matching score in restricted_data.
-- pass_status starts 'not_assessed' so the lecturer re-import journey can flip
-- it to 'passed' without depending on other specs.
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('a0000001-0000-0000-0000-000000000001', 'd000000e-0000-0000-0000-00000000000e', '{"score": 90}', 'not_assessed', '{}');
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('ca000008-0000-4000-8000-000000000008', 'd000000e-0000-0000-0000-00000000000e', '{"score": 85}', 'not_assessed', '{}');
-- Certificate phases (see the course_phase inserts below): Stan participates in
-- the graph-tail phase (smoke + API reads) and both standalone journey phases
-- (lecturer participants table + staff download, student self-download).
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('a0000001-0000-0000-0000-000000000001', 'd000000d-0000-0000-0000-00000000000d', '{}', 'passed', '{}');
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('a0000001-0000-0000-0000-000000000001', 'd000000a-0000-0000-0000-00000000000a', '{}', 'passed', '{}');
INSERT INTO public.course_phase_participation (course_participation_id, course_phase_id, restricted_data, pass_status, student_readable_data) VALUES ('a0000001-0000-0000-0000-000000000001', 'd000000b-0000-0000-0000-00000000000b', '{}', 'passed', '{}');



--
-- Data for Name: course_phase_type; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.course_phase_type VALUES ('a1111111-1111-1111-1111-111111111111', 'Application', true, 'core', 'Application collection phase');
INSERT INTO public.course_phase_type VALUES ('a2222222-2222-2222-2222-222222222222', 'Example', false, 'example', 'Example phase');
-- Fixed UUIDs so seeded course phases can reference these types deterministically; the
-- core server's startup init matches by name and skips creating them (it would
-- otherwise use random UUIDs). {CORE_HOST} is replaced by core at read time.
-- The b-series types match servers/core/coursePhaseType/initializeTypes.go by name.
INSERT INTO public.course_phase_type VALUES ('a3333333-3333-3333-3333-333333333333', 'Self Team Allocation', false, '{CORE_HOST}/self-team-allocation/api', 'Students form teams themselves');
INSERT INTO public.course_phase_type VALUES ('b1111111-1111-1111-1111-111111111111', 'Interview', false, '{CORE_HOST}/interview/api', 'Interview phase for student assessments and scheduling.');
INSERT INTO public.course_phase_type VALUES ('b2222222-2222-2222-2222-222222222222', 'Matching', false, 'core', 'A placeholder description for this course phase type. Detailed description will follow.');
INSERT INTO public.course_phase_type VALUES ('b3333333-3333-3333-3333-333333333333', 'Team Allocation', false, '{CORE_HOST}/team-allocation/api', 'A placeholder description for this course phase type. Detailed description will follow.');
INSERT INTO public.course_phase_type VALUES ('b4444444-4444-4444-4444-444444444444', 'Assessment', false, '{CORE_HOST}/assessment/api', 'A placeholder description for this course phase type. Detailed description will follow.');
INSERT INTO public.course_phase_type VALUES ('c5555555-5555-5555-5555-555555555555', 'Certificate', false, '{CORE_HOST}/certificate/api', 'Certificate of completion generation and distribution.');


--
-- An open Application phase on iPraktikum, so the file-upload endpoints accept
-- uploads (applicationEndDate in the future → CheckIfCoursePhaseIsOpenApplicationPhase passes).
-- applicationStartDate + explicit externalStudentsAllowed are required by the stricter
-- GetOpenApplicationPhase query that backs the public /apply form (start<NOW; non-null bool casts).
--

INSERT INTO public.course_phase VALUES ('aaaa1111-0000-0000-0000-0000000000a1', 'd7307be2-d3dc-496e-86f0-643bff6cc1c8', 'Application', '{"applicationStartDate": "2020-01-01T00:00:00", "applicationEndDate": "2099-12-31T23:59:59", "externalStudentsAllowed": false, "universityLoginAvailable": false}', true, 'a1111111-1111-1111-1111-111111111111', '{}');

--
-- A Self Team Allocation phase on iPraktikum (follows Application in the
-- graph), plus one on TestCourse with no participants and no graph edge: the
-- negative-auth fixture (the e2e students are not enrolled in TestCourse).
-- Plus the full phase graph for iPraktikumFull: Application -> Interview ->
-- Matching -> Team Allocation -> Assessment. Its Application phase is open
-- (start in the past, end in the far future) so it also qualifies as an open
-- application phase.
--

INSERT INTO public.course_phase VALUES ('aaaa2222-0000-0000-0000-0000000000a2', 'd7307be2-d3dc-496e-86f0-643bff6cc1c8', 'Self Team Allocation', '{}', false, 'a3333333-3333-3333-3333-333333333333', '{}');
INSERT INTO public.course_phase VALUES ('aaaa3333-0000-0000-0000-0000000000a3', 'be780b32-a678-4b79-ae1c-80071771d254', 'Self Team Allocation', '{}', false, 'a3333333-3333-3333-3333-333333333333', '{}');
-- Standalone (no graph edge) phase owned by the lecturer-overview spec: teams
-- formed there never collide with the student journey's phase when Playwright
-- runs the two spec files in parallel workers.
INSERT INTO public.course_phase VALUES ('aaaa4444-0000-0000-0000-0000000000a4', 'd7307be2-d3dc-496e-86f0-643bff6cc1c8', 'Self Team Allocation Overview', '{}', false, 'a3333333-3333-3333-3333-333333333333', '{}');
INSERT INTO public.course_phase VALUES ('d0000001-0000-0000-0000-000000000001', 'c0000001-0000-0000-0000-000000000001', 'Application', '{"applicationStartDate": "2020-01-01T00:00:00", "applicationEndDate": "2099-12-31T23:59:59", "externalStudentsAllowed": true, "universityLoginAvailable": false}', true, 'a1111111-1111-1111-1111-111111111111', '{}');
INSERT INTO public.course_phase VALUES ('d0000002-0000-0000-0000-000000000002', 'c0000001-0000-0000-0000-000000000001', 'Interview', '{}', false, 'b1111111-1111-1111-1111-111111111111', '{}');
INSERT INTO public.course_phase VALUES ('d0000003-0000-0000-0000-000000000003', 'c0000001-0000-0000-0000-000000000001', 'Matching', '{}', false, 'b2222222-2222-2222-2222-222222222222', '{}');
INSERT INTO public.course_phase VALUES ('d0000004-0000-0000-0000-000000000004', 'c0000001-0000-0000-0000-000000000001', 'Team Allocation', '{}', false, 'b3333333-3333-3333-3333-333333333333', '{}');
INSERT INTO public.course_phase VALUES ('d0000005-0000-0000-0000-000000000005', 'c0000001-0000-0000-0000-000000000001', 'Assessment', '{}', false, 'b4444444-4444-4444-4444-444444444444', '{}');

--
-- Standalone assessment fixture phases (no graph edges — the graph's UNIQUE
-- from/to constraints force a chain, and non-graph phases still route by URL,
-- they are just filtered from the course sidebar). One phase per spec file so
-- release state and schema locking never cross parallel Playwright files:
-- d0000006 = student visibility spec (Stan + Selma participate),
-- d0000007 = self-evaluation spec (Stan participates),
-- d0000008 = TestCourse negative-auth fixture (no participants; the e2e
-- students are not enrolled in TestCourse),
-- d0000009 = print spec (Stan participates).
--

INSERT INTO public.course_phase VALUES ('d0000006-0000-0000-0000-000000000006', 'c0000001-0000-0000-0000-000000000001', 'Assessment Visibility', '{}', false, 'b4444444-4444-4444-4444-444444444444', '{}');
INSERT INTO public.course_phase VALUES ('d0000007-0000-0000-0000-000000000007', 'c0000001-0000-0000-0000-000000000001', 'Assessment Self Evaluation', '{}', false, 'b4444444-4444-4444-4444-444444444444', '{}');
INSERT INTO public.course_phase VALUES ('d0000008-0000-0000-0000-000000000008', 'be780b32-a678-4b79-ae1c-80071771d254', 'Assessment', '{}', false, 'b4444444-4444-4444-4444-444444444444', '{}');
INSERT INTO public.course_phase VALUES ('d0000009-0000-0000-0000-000000000009', 'c0000001-0000-0000-0000-000000000001', 'Assessment Print', '{}', false, 'b4444444-4444-4444-4444-444444444444', '{}');

--
-- Standalone Matching phase (no graph edge) owned by the matching lecturer
-- re-import spec, so its pass_status mutation never collides with the graph
-- Matching phase (d0000003) used by the smoke / student / API specs.
--

INSERT INTO public.course_phase VALUES ('d000000e-0000-0000-0000-00000000000e', 'c0000001-0000-0000-0000-000000000001', 'Matching Re-Import', '{}', false, 'b2222222-2222-2222-2222-222222222222', '{}');

--
-- A CLOSED Application phase on TestCourse (applicationEndDate in the past):
-- the negative fixture for the public apply endpoints (GET 404, POST 400).
-- TestCourse has no other initial phase, so unique_initial_phase_per_course holds.
--

INSERT INTO public.course_phase VALUES ('aaaa5555-0000-0000-0000-0000000000a5', 'be780b32-a678-4b79-ae1c-80071771d254', 'Application', '{"applicationStartDate": "2020-01-01T00:00:00", "applicationEndDate": "2020-06-30T23:59:59", "externalStudentsAllowed": true, "universityLoginAvailable": false}', true, 'a1111111-1111-1111-1111-111111111111', '{}');

--
-- Certificate phases. d000000d is the graph-tail phase on iPraktikumFull
-- (smoke + API-auth reads, left unconfigured). d000000a / d000000b are
-- standalone fixtures (no graph edge, route by URL) so the lecturer journey's
-- template/release state and the student journey's downloads never cross when
-- Playwright runs the spec files in parallel. d000000c is the TestCourse
-- negative-auth fixture (no participants; the e2e students are not enrolled).
--

INSERT INTO public.course_phase VALUES ('d000000d-0000-0000-0000-00000000000d', 'c0000001-0000-0000-0000-000000000001', 'Certificate', '{}', false, 'c5555555-5555-5555-5555-555555555555', '{}');
INSERT INTO public.course_phase VALUES ('d000000a-0000-0000-0000-00000000000a', 'c0000001-0000-0000-0000-000000000001', 'Certificate Lecturer', '{}', false, 'c5555555-5555-5555-5555-555555555555', '{}');
INSERT INTO public.course_phase VALUES ('d000000b-0000-0000-0000-00000000000b', 'c0000001-0000-0000-0000-000000000001', 'Certificate Student', '{}', false, 'c5555555-5555-5555-5555-555555555555', '{}');
INSERT INTO public.course_phase VALUES ('d000000c-0000-0000-0000-00000000000c', 'be780b32-a678-4b79-ae1c-80071771d254', 'Certificate', '{}', false, 'c5555555-5555-5555-5555-555555555555', '{}');

--
-- Standalone interview fixture phase (no graph edge, see above):
-- aaaa6666 = TestCourse negative-auth fixture for the interview API (no
-- participants; the e2e users hold no TestCourse roles).
--

INSERT INTO public.course_phase VALUES ('aaaa6666-0000-0000-0000-0000000000a6', 'be780b32-a678-4b79-ae1c-80071771d254', 'Interview', '{}', false, 'b1111111-1111-1111-1111-111111111111', '{}');


--
-- Data for Name: course_phase_type_participation_provided_output_dto; Type: TABLE DATA; Schema: public; Owner: -
--

-- Mirrors core's InsertTeamAllocationOutput (skipped at startup because the
-- phase type above already exists).
INSERT INTO public.course_phase_type_participation_provided_output_dto VALUES ('d1000001-0000-4000-8000-000000000001', 'a3333333-3333-3333-3333-333333333333', 'teamAllocation', 1, '/allocation', '{"type": "string"}');
-- Mirrors core's InsertAssessmentScoreOutput / InsertActionItemsOutput /
-- InsertGradeOutput for the Assessment type.
INSERT INTO public.course_phase_type_participation_provided_output_dto VALUES ('d1000003-0000-4000-8000-000000000003', 'b4444444-4444-4444-4444-444444444444', 'scoreLevel', 1, '/student-assessment/scoreLevel', '{"type": "string", "enum": ["veryBad", "bad", "ok", "good", "veryGood"]}');
INSERT INTO public.course_phase_type_participation_provided_output_dto VALUES ('d1000004-0000-4000-8000-000000000004', 'b4444444-4444-4444-4444-444444444444', 'actionItems', 1, '/student-assessment/action-item/action', '{"type": "array", "items": {"type": "string"}}');
INSERT INTO public.course_phase_type_participation_provided_output_dto VALUES ('d1000005-0000-4000-8000-000000000005', 'b4444444-4444-4444-4444-444444444444', 'grade', 1, '/student-assessment/completed/grade', '{"type": "number"}');


--
-- Data for Name: course_phase_type_participation_required_input_dto; Type: TABLE DATA; Schema: public; Owner: -
--

-- Mirrors core's InsertTeamAllocationRequiredInput for the Assessment type.
INSERT INTO public.course_phase_type_participation_required_input_dto VALUES ('d1000006-0000-4000-8000-000000000006', 'b4444444-4444-4444-4444-444444444444', 'teamAllocation', '{"type": "string"}');
-- Mirrors core's InsertTeamAllocationRequiredInput for the Certificate type.
INSERT INTO public.course_phase_type_participation_required_input_dto VALUES ('d1000008-0000-4000-8000-000000000008', 'c5555555-5555-5555-5555-555555555555', 'teamAllocation', '{"type": "string"}');


--
-- Data for Name: course_phase_type_phase_provided_output_dto; Type: TABLE DATA; Schema: public; Owner: -
--

-- Mirrors core's InsertTeamOutput.
INSERT INTO public.course_phase_type_phase_provided_output_dto VALUES ('d1000002-0000-4000-8000-000000000002', 'a3333333-3333-3333-3333-333333333333', 'teams', 1, '/team', '{"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "name": {"type": "string"}}, "required": ["id", "name"]}}');


--
-- Data for Name: course_phase_type_phase_required_input_dto; Type: TABLE DATA; Schema: public; Owner: -
--

-- Mirrors core's InsertTeamRequiredInput for the Assessment type.
INSERT INTO public.course_phase_type_phase_required_input_dto VALUES ('d1000007-0000-4000-8000-000000000007', 'b4444444-4444-4444-4444-444444444444', 'teams', '{"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "name": {"type": "string"}}, "required": ["id", "name"]}}');
-- Mirrors core's InsertTeamRequiredInput for the Certificate type.
INSERT INTO public.course_phase_type_phase_required_input_dto VALUES ('d1000009-0000-4000-8000-000000000009', 'c5555555-5555-5555-5555-555555555555', 'teams', '{"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "name": {"type": "string"}}, "required": ["id", "name"]}}');



--
-- Data for Name: files; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: note; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: note_tag; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: note_tag_relation; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: note_version; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: participation_data_dependency_graph; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: phase_data_dependency_graph; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: privacy_export; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: privacy_export_document; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.schema_migrations VALUES (24, false);


--
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.student VALUES ('3869f209-9a21-4595-ae0e-bc6d6a3e2d63', 'Niclas', 'Heun', 'niclas.heun@tum.de', '03711126', 'ge25hok', true, 'male', 'DE', 'Computer Science', 'master', 19, '2025-01-09 18:20:28.256593');
INSERT INTO public.student VALUES ('402e1535-fb9c-494f-82f2-ab4d39d71155', 'super long text', 'Text test', 'test@supertest.de', '', '', false, 'prefer_not_to_say', 'AI', 'test', 'bachelor', 5, '2025-01-14 09:48:07.641231');
INSERT INTO public.student VALUES ('5eb545c2-c2eb-4c77-9c0f-46ccf7c45d07', 'Niclas', 'Heun', 'niclas@heun.ent', '08888888', 'uu66uuu', true, 'male', 'DE', 'Computer Science', 'master', 12, '2025-01-08 14:30:29.553373');
INSERT INTO public.student VALUES ('bb9736b4-076f-4592-8197-9a839ac115fb', 'Test User', 'User-Last_Nam', 'niclas10@test.de', '09111999', 'ge77hok', true, 'diverse', NULL, NULL, 'bachelor', NULL, '2025-01-07 18:21:19.97367');
INSERT INTO public.student VALUES ('afd0cc74-7218-4f3a-8c2b-ef88aa5a9b1e', 'Test User', 'TEst', 'test@test.de', '09987652', 'ab00lll', true, 'diverse', NULL, NULL, 'bachelor', NULL, '2025-01-07 18:21:19.97367');
INSERT INTO public.student VALUES ('ac3d8139-723f-4d8f-89c8-b7171b41b0d3', 'Test', 'test', 'test3@test3.de', '05555555', 'hh77hhh', true, 'female', NULL, NULL, 'bachelor', NULL, '2025-01-07 18:21:19.97367');
INSERT INTO public.student VALUES ('9c157166-dd37-42f6-98ab-f5fda439ced1', 'Niclas', 'Heun', 'niclas@heun.net', '', '', false, 'diverse', 'AD', 'Information Systems', 'bachelor', 5, '2025-01-08 18:29:02.512604');
INSERT INTO public.student VALUES ('2428d311-4ad4-4d91-a46e-e5e2a5a4a3ee', 'Test', 'Test', 'test2@test.de', '04511126', 'ge88hok', true, 'diverse', 'DZ', 'Information Systems', 'bachelor', 10, '2025-01-08 18:33:36.571565');
INSERT INTO public.student VALUES ('33f49be1-0106-4642-8a8c-d492c841118a', 'Test', 'Supertest', 'supertest@test.de', '08888889', 'ab00hhh', true, 'diverse', 'AD', 'Information Systems', 'bachelor', 5, '2025-01-08 18:36:09.56128');
INSERT INTO public.student VALUES ('777286f4-a3e7-4bcd-bf57-13d178bf582d', 'New Test', 'user', 'niclas@heun.io', '09999222', 'oo55ooo', true, 'female', 'DZ', 'Computer Science', 'bachelor', 5, '2025-01-08 18:39:34.368859');
INSERT INTO public.student VALUES ('1e41e383-2c3f-4149-bd67-54e41cdaebec', 'test-lol', 'test', 'niclas@test.de', '09999999', 'as45fgh', true, 'female', 'AL', 'Information Systems', 'bachelor', 5, '2025-01-08 18:42:55.407307');
INSERT INTO public.student VALUES ('28880f4d-6f8a-4826-a7c6-e2f295f6ff72', 'Stefan', 'Heun', 'stefan@heun.io', '', '', false, 'male', 'DE', 'Computer Science', 'master', 12, '2025-01-08 20:55:17.282497');
INSERT INTO public.student VALUES ('23bf3123-4f0d-473c-9ef5-d0333e29fe9a', 'Max', 'Mustermann', 'max.mustermann@tum.de', '09822222', 'ji79klj', true, 'male', NULL, NULL, 'bachelor', NULL, '2025-01-07 18:21:19.97367');
INSERT INTO public.student VALUES ('6381660e-6f30-4632-bfd0-5b7dd92c6fcf', 'test', 'student', 'looool@tum.de', '', '', false, 'diverse', 'AL', NULL, 'bachelor', NULL, '2025-01-07 18:21:19.97367');
INSERT INTO public.student VALUES ('5f2c6b09-b170-48a1-a6cf-30c7688df1f4', 'Nationality Test', 'Registered User', 'nation@test.de', '08877663', 'ab69lol', true, 'male', 'DE', NULL, 'bachelor', NULL, '2025-01-07 18:21:19.97367');
INSERT INTO public.student VALUES ('65828d3e-11bc-4168-8edc-3968b53f4f83', 'External ', 'TEst', 'amazing@test.de', '', '', false, 'female', 'DK', NULL, 'bachelor', NULL, '2025-01-07 18:21:19.97367');
INSERT INTO public.student VALUES ('2d8c24b4-b91a-4219-9bd8-3f2502774ebc', 'Test-100', 'User-Update', 'user@test.de', '', '', false, 'diverse', 'AL', NULL, 'bachelor', NULL, '2025-01-07 18:22:05.814353');
INSERT INTO public.student VALUES ('1c62c564-491b-43e3-9929-7be39509e32e', 'Niclas', 'Heun', 'test@leeeeeel.de', '00000000', 'hh88hhh', true, 'female', 'DE', 'Computer Science', 'master', 5, '2025-01-07 22:50:17.814704');
INSERT INTO public.student VALUES ('5939210d-5c47-446e-ba55-3da992fd7aa6', 'Niclas', 'Heuni', 'heuni@heuni.de', '', '', false, 'prefer_not_to_say', 'DE', 'Information Systems', 'bachelor', 5, '2025-01-07 23:05:43.120086');
-- The two Keycloak e2e student users (matriculation_number/university_login
-- must match the realm user attributes in e2e/keycloak/realm.json). `student`
-- (Stan, 00000005/no42tum) is also the iPraktikumFull participant a0000001, so
-- its full-course participation resolves to a DB-derived Student role.
INSERT INTO public.student VALUES ('e0000005-0000-0000-0000-000000000005', 'Stan', 'Stan', 'pgdp_enjoyer@example.com', '00000005', 'no42tum', true, 'male', 'DE', 'Computer Science', 'bachelor', 3, '2025-01-09 12:00:00.000000');
INSERT INTO public.student VALUES ('a5000007-0000-4000-8000-000000000007', 'Selma', 'Second', 'second_student@example.com', '00000007', 'st70two', true, 'female', 'DE', 'Computer Science', 'bachelor', 3, '2025-01-09 12:00:00.000000');


--
-- Name: application_answer_file_upload application_answer_file_upload_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_file_upload
    ADD CONSTRAINT application_answer_file_upload_pkey PRIMARY KEY (id);


--
-- Name: application_answer_multi_select application_answer_multi_select_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_multi_select
    ADD CONSTRAINT application_answer_multi_select_pkey PRIMARY KEY (id);


--
-- Name: application_answer_text application_answer_text_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_text
    ADD CONSTRAINT application_answer_text_pkey PRIMARY KEY (id);


--
-- Name: application_assessment application_assessment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_assessment
    ADD CONSTRAINT application_assessment_pkey PRIMARY KEY (id);


--
-- Name: application_question_file_upload application_question_file_upload_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_question_file_upload
    ADD CONSTRAINT application_question_file_upload_pkey PRIMARY KEY (id);


--
-- Name: application_question_multi_select application_question_multi_select_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_question_multi_select
    ADD CONSTRAINT application_question_multi_select_pkey PRIMARY KEY (id);


--
-- Name: application_question_text application_question_text_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_question_text
    ADD CONSTRAINT application_question_text_pkey PRIMARY KEY (id);


--
-- Name: course_participation course_participation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_participation
    ADD CONSTRAINT course_participation_pkey PRIMARY KEY (id);


--
-- Name: course_phase_participation course_phase_participation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_participation
    ADD CONSTRAINT course_phase_participation_pkey PRIMARY KEY (course_participation_id, course_phase_id);


--
-- Name: course_phase course_phase_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase
    ADD CONSTRAINT course_phase_pkey PRIMARY KEY (id);


--
-- Name: course_phase_type course_phase_type_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_type
    ADD CONSTRAINT course_phase_type_name_key UNIQUE (name);


--
-- Name: course_phase_type_phase_provided_output_dto course_phase_type_phase_provided_output_dto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_type_phase_provided_output_dto
    ADD CONSTRAINT course_phase_type_phase_provided_output_dto_pkey PRIMARY KEY (id);


--
-- Name: course_phase_type_phase_required_input_dto course_phase_type_phase_required_input_dto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_type_phase_required_input_dto
    ADD CONSTRAINT course_phase_type_phase_required_input_dto_pkey PRIMARY KEY (id);


--
-- Name: course_phase_type course_phase_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_type
    ADD CONSTRAINT course_phase_type_pkey PRIMARY KEY (id);


--
-- Name: course_phase_type_participation_provided_output_dto course_phase_type_provided_output_dto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_type_participation_provided_output_dto
    ADD CONSTRAINT course_phase_type_provided_output_dto_pkey PRIMARY KEY (id);


--
-- Name: course_phase_type_participation_required_input_dto course_phase_type_required_input_dto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_type_participation_required_input_dto
    ADD CONSTRAINT course_phase_type_required_input_dto_pkey PRIMARY KEY (id);


--
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- Name: files files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_pkey PRIMARY KEY (id);


--
-- Name: files files_storage_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_storage_key_key UNIQUE (storage_key);


--
-- Name: participation_data_dependency_graph meta_data_dependency_graph_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participation_data_dependency_graph
    ADD CONSTRAINT meta_data_dependency_graph_pkey PRIMARY KEY (to_course_phase_id, to_course_phase_dto_id);


--
-- Name: note note_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note
    ADD CONSTRAINT note_pkey PRIMARY KEY (id);


--
-- Name: note_tag note_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tag
    ADD CONSTRAINT note_tag_name_key UNIQUE (name);


--
-- Name: note_tag note_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tag
    ADD CONSTRAINT note_tag_pkey PRIMARY KEY (id);


--
-- Name: note_tag_relation note_tag_relation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tag_relation
    ADD CONSTRAINT note_tag_relation_pkey PRIMARY KEY (note_id, tag_id);


--
-- Name: note_version note_version_for_note_version_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_version
    ADD CONSTRAINT note_version_for_note_version_number_key UNIQUE (for_note, version_number);


--
-- Name: note_version note_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_version
    ADD CONSTRAINT note_version_pkey PRIMARY KEY (id);


--
-- Name: phase_data_dependency_graph phase_data_dependency_graph_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phase_data_dependency_graph
    ADD CONSTRAINT phase_data_dependency_graph_pkey PRIMARY KEY (to_course_phase_id, to_course_phase_dto_id);


--
-- Name: privacy_export_document privacy_export_document_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.privacy_export_document
    ADD CONSTRAINT privacy_export_document_pkey PRIMARY KEY (id);


--
-- Name: privacy_export privacy_export_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.privacy_export
    ADD CONSTRAINT privacy_export_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: student student_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_email_key UNIQUE (email);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);


--
-- Name: application_answer_multi_select unique_application_answer_multi_select; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_multi_select
    ADD CONSTRAINT unique_application_answer_multi_select UNIQUE (course_participation_id, application_question_id);


--
-- Name: application_answer_text unique_application_answer_text; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_text
    ADD CONSTRAINT unique_application_answer_text UNIQUE (course_participation_id, application_question_id);


--
-- Name: course unique_course_identifier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT unique_course_identifier UNIQUE (name, semester_tag);


--
-- Name: course_participation unique_course_participation; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_participation
    ADD CONSTRAINT unique_course_participation UNIQUE (course_id, student_id);


--
-- Name: course_phase_participation unique_course_phase_participation; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_participation
    ADD CONSTRAINT unique_course_phase_participation UNIQUE (course_participation_id, course_phase_id);


--
-- Name: application_assessment unique_course_phase_participation_assessment; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_assessment
    ADD CONSTRAINT unique_course_phase_participation_assessment UNIQUE (course_phase_id, course_participation_id);


--
-- Name: application_answer_file_upload unique_file_upload_answer; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_file_upload
    ADD CONSTRAINT unique_file_upload_answer UNIQUE (course_participation_id, application_question_id);


--
-- Name: course_phase_graph unique_from_course_phase; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_graph
    ADD CONSTRAINT unique_from_course_phase UNIQUE (from_course_phase_id);


--
-- Name: course_phase_graph unique_to_course_phase; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_graph
    ADD CONSTRAINT unique_to_course_phase UNIQUE (to_course_phase_id);


--
-- Name: idx_application_answer_file_upload_file; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_application_answer_file_upload_file ON public.application_answer_file_upload USING btree (file_id);


--
-- Name: idx_application_answer_file_upload_participation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_application_answer_file_upload_participation ON public.application_answer_file_upload USING btree (course_participation_id);


--
-- Name: idx_application_answer_file_upload_question; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_application_answer_file_upload_question ON public.application_answer_file_upload USING btree (application_question_id);


--
-- Name: idx_application_question_file_upload_course_phase_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_application_question_file_upload_course_phase_id ON public.application_question_file_upload USING btree (course_phase_id);


--
-- Name: idx_application_question_file_upload_order_num; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_application_question_file_upload_order_num ON public.application_question_file_upload USING btree (course_phase_id, order_num);


--
-- Name: idx_files_course_phase_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_files_course_phase_id ON public.files USING btree (course_phase_id) WHERE (course_phase_id IS NOT NULL);


--
-- Name: idx_files_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_files_created_at ON public.files USING btree (created_at DESC);


--
-- Name: idx_files_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_files_deleted_at ON public.files USING btree (deleted_at) WHERE (deleted_at IS NULL);


--
-- Name: idx_files_storage_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_files_storage_key ON public.files USING btree (storage_key);


--
-- Name: idx_files_uploaded_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_files_uploaded_by ON public.files USING btree (uploaded_by_user_id);


--
-- Name: idx_note_for_student_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_note_for_student_deleted ON public.note USING btree (for_student, date_deleted);


--
-- Name: idx_note_tag_note_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_note_tag_note_id ON public.note_tag_relation USING btree (note_id);


--
-- Name: idx_note_tag_tag_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_note_tag_tag_id ON public.note_tag_relation USING btree (tag_id);


--
-- Name: student_matriculation_number_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX student_matriculation_number_unique ON public.student USING btree (matriculation_number) WHERE ((matriculation_number IS NOT NULL) AND ((matriculation_number)::text <> ''::text));


--
-- Name: student_university_login_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX student_university_login_unique ON public.student USING btree (university_login) WHERE ((university_login IS NOT NULL) AND ((university_login)::text <> ''::text));


--
-- Name: unique_initial_phase_per_course; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_initial_phase_per_course ON public.course_phase USING btree (course_id) WHERE (is_initial_phase = true);


--
-- Name: note_with_versions _RETURN; Type: RULE; Schema: public; Owner: -
--

CREATE OR REPLACE VIEW public.note_with_versions AS
 SELECT n.id,
    n.author,
    n.author_name,
    n.author_email,
    n.for_student,
    n.date_created,
    n.date_deleted,
    n.deleted_by,
        CASE
            WHEN (n.date_deleted IS NULL) THEN jsonb_agg(jsonb_build_object('id', nv.id, 'content', nv.content, 'dateCreated', nv.date_created, 'versionNumber', nv.version_number) ORDER BY nv.version_number)
            ELSE '[]'::jsonb
        END AS versions,
        CASE
            WHEN (n.date_deleted IS NULL) THEN COALESCE(( SELECT jsonb_agg(jsonb_build_object('id', nt.id, 'name', nt.name, 'color', nt.color) ORDER BY nt.name) AS jsonb_agg
               FROM (public.note_tag_relation ntr
                 JOIN public.note_tag nt ON ((nt.id = ntr.tag_id)))
              WHERE (ntr.note_id = n.id)), '[]'::jsonb)
            ELSE '[]'::jsonb
        END AS tags
   FROM (public.note n
     JOIN public.note_version nv ON ((nv.for_note = n.id)))
  GROUP BY n.id;


--
-- Name: privacy_export_with_docs _RETURN; Type: RULE; Schema: public; Owner: -
--

CREATE OR REPLACE VIEW public.privacy_export_with_docs AS
 SELECT e.id,
    e.user_id,
    e.student_id,
    e.status,
    e.date_created,
    e.valid_until,
    e.next_request_allowed_at,
    COALESCE(jsonb_agg(jsonb_build_object('id', ed.id, 'date_created', ed.date_created, 'source_name', ed.source_name, 'status', ed.status, 'file_size', ed.file_size, 'downloaded_at', ed.downloaded_at) ORDER BY ed.date_created) FILTER (WHERE (ed.id IS NOT NULL)), '[]'::jsonb) AS documents
   FROM (public.privacy_export e
     LEFT JOIN public.privacy_export_document ed ON ((ed.export_id = e.id)))
  GROUP BY e.id;


--
-- Name: course_phase_participation set_last_modified_course_phase_participation; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_last_modified_course_phase_participation BEFORE UPDATE ON public.course_phase_participation FOR EACH ROW EXECUTE FUNCTION public.update_last_modified_column();


--
-- Name: student set_last_modified_student; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_last_modified_student BEFORE UPDATE ON public.student FOR EACH ROW EXECUTE FUNCTION public.update_last_modified_column();


--
-- Name: files trigger_update_files_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_files_updated_at BEFORE UPDATE ON public.files FOR EACH ROW EXECUTE FUNCTION public.update_files_updated_at();


--
-- Name: application_answer_file_upload fk_application_answer_file_upload_file; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_file_upload
    ADD CONSTRAINT fk_application_answer_file_upload_file FOREIGN KEY (file_id) REFERENCES public.files(id) ON DELETE CASCADE;


--
-- Name: application_answer_file_upload fk_application_answer_file_upload_participation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_file_upload
    ADD CONSTRAINT fk_application_answer_file_upload_participation FOREIGN KEY (course_participation_id) REFERENCES public.course_participation(id) ON DELETE CASCADE;


--
-- Name: application_answer_file_upload fk_application_answer_file_upload_question; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_file_upload
    ADD CONSTRAINT fk_application_answer_file_upload_question FOREIGN KEY (application_question_id) REFERENCES public.application_question_file_upload(id) ON DELETE CASCADE;


--
-- Name: application_answer_multi_select fk_application_question; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_multi_select
    ADD CONSTRAINT fk_application_question FOREIGN KEY (application_question_id) REFERENCES public.application_question_multi_select(id) ON DELETE CASCADE;


--
-- Name: application_answer_text fk_application_question; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_text
    ADD CONSTRAINT fk_application_question FOREIGN KEY (application_question_id) REFERENCES public.application_question_text(id) ON DELETE CASCADE;


--
-- Name: application_question_file_upload fk_application_question_file_upload_course_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_question_file_upload
    ADD CONSTRAINT fk_application_question_file_upload_course_phase FOREIGN KEY (course_phase_id) REFERENCES public.course_phase(id) ON DELETE CASCADE;


--
-- Name: course_participation fk_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_participation
    ADD CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES public.course(id) ON DELETE CASCADE;


--
-- Name: course_phase fk_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase
    ADD CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES public.course(id) ON DELETE CASCADE;


--
-- Name: application_answer_multi_select fk_course_participation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_multi_select
    ADD CONSTRAINT fk_course_participation FOREIGN KEY (course_participation_id) REFERENCES public.course_participation(id) ON DELETE CASCADE;


--
-- Name: application_answer_text fk_course_participation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_answer_text
    ADD CONSTRAINT fk_course_participation FOREIGN KEY (course_participation_id) REFERENCES public.course_participation(id) ON DELETE CASCADE;


--
-- Name: course_phase_participation fk_course_participation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_participation
    ADD CONSTRAINT fk_course_participation FOREIGN KEY (course_participation_id) REFERENCES public.course_participation(id) ON DELETE CASCADE;


--
-- Name: application_question_multi_select fk_course_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_question_multi_select
    ADD CONSTRAINT fk_course_phase FOREIGN KEY (course_phase_id) REFERENCES public.course_phase(id) ON DELETE CASCADE;


--
-- Name: application_question_text fk_course_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_question_text
    ADD CONSTRAINT fk_course_phase FOREIGN KEY (course_phase_id) REFERENCES public.course_phase(id) ON DELETE CASCADE;


--
-- Name: course_phase_participation fk_course_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_participation
    ADD CONSTRAINT fk_course_phase FOREIGN KEY (course_phase_id) REFERENCES public.course_phase(id) ON DELETE CASCADE;


--
-- Name: application_assessment fk_course_phase_participation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_assessment
    ADD CONSTRAINT fk_course_phase_participation FOREIGN KEY (course_participation_id, course_phase_id) REFERENCES public.course_phase_participation(course_participation_id, course_phase_id) ON DELETE CASCADE;


--
-- Name: course_phase_type_phase_provided_output_dto fk_course_phase_type_phase_provided; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_type_phase_provided_output_dto
    ADD CONSTRAINT fk_course_phase_type_phase_provided FOREIGN KEY (course_phase_type_id) REFERENCES public.course_phase_type(id) ON DELETE CASCADE;


--
-- Name: course_phase_type_phase_required_input_dto fk_course_phase_type_phase_required; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_type_phase_required_input_dto
    ADD CONSTRAINT fk_course_phase_type_phase_required FOREIGN KEY (course_phase_type_id) REFERENCES public.course_phase_type(id) ON DELETE CASCADE;


--
-- Name: course_phase_type_participation_provided_output_dto fk_course_phase_type_provided; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_type_participation_provided_output_dto
    ADD CONSTRAINT fk_course_phase_type_provided FOREIGN KEY (course_phase_type_id) REFERENCES public.course_phase_type(id) ON DELETE CASCADE;


--
-- Name: course_phase_type_participation_required_input_dto fk_course_phase_type_required; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_type_participation_required_input_dto
    ADD CONSTRAINT fk_course_phase_type_required FOREIGN KEY (course_phase_type_id) REFERENCES public.course_phase_type(id) ON DELETE CASCADE;


--
-- Name: files fk_files_course_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT fk_files_course_phase FOREIGN KEY (course_phase_id) REFERENCES public.course_phase(id) ON DELETE SET NULL;


--
-- Name: course_phase_graph fk_from_course_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_graph
    ADD CONSTRAINT fk_from_course_phase FOREIGN KEY (from_course_phase_id) REFERENCES public.course_phase(id) ON DELETE CASCADE;


--
-- Name: participation_data_dependency_graph fk_from_dto; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participation_data_dependency_graph
    ADD CONSTRAINT fk_from_dto FOREIGN KEY (from_course_phase_dto_id) REFERENCES public.course_phase_type_participation_provided_output_dto(id) ON DELETE CASCADE;


--
-- Name: phase_data_dependency_graph fk_from_dto_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phase_data_dependency_graph
    ADD CONSTRAINT fk_from_dto_phase FOREIGN KEY (from_course_phase_dto_id) REFERENCES public.course_phase_type_phase_provided_output_dto(id) ON DELETE CASCADE;


--
-- Name: participation_data_dependency_graph fk_from_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participation_data_dependency_graph
    ADD CONSTRAINT fk_from_phase FOREIGN KEY (from_course_phase_id) REFERENCES public.course_phase(id) ON DELETE CASCADE;


--
-- Name: phase_data_dependency_graph fk_from_phase_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phase_data_dependency_graph
    ADD CONSTRAINT fk_from_phase_phase FOREIGN KEY (from_course_phase_id) REFERENCES public.course_phase(id) ON DELETE CASCADE;


--
-- Name: course_phase fk_phase_type; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase
    ADD CONSTRAINT fk_phase_type FOREIGN KEY (course_phase_type_id) REFERENCES public.course_phase_type(id);


--
-- Name: course_participation fk_student; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_participation
    ADD CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES public.student(id) ON DELETE CASCADE;


--
-- Name: course_phase_graph fk_to_course_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_phase_graph
    ADD CONSTRAINT fk_to_course_phase FOREIGN KEY (to_course_phase_id) REFERENCES public.course_phase(id) ON DELETE CASCADE;


--
-- Name: participation_data_dependency_graph fk_to_dto; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participation_data_dependency_graph
    ADD CONSTRAINT fk_to_dto FOREIGN KEY (to_course_phase_dto_id) REFERENCES public.course_phase_type_participation_required_input_dto(id) ON DELETE CASCADE;


--
-- Name: phase_data_dependency_graph fk_to_dto_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phase_data_dependency_graph
    ADD CONSTRAINT fk_to_dto_phase FOREIGN KEY (to_course_phase_dto_id) REFERENCES public.course_phase_type_phase_required_input_dto(id) ON DELETE CASCADE;


--
-- Name: participation_data_dependency_graph fk_to_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participation_data_dependency_graph
    ADD CONSTRAINT fk_to_phase FOREIGN KEY (to_course_phase_id) REFERENCES public.course_phase(id) ON DELETE CASCADE;


--
-- Name: phase_data_dependency_graph fk_to_phase_phase; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phase_data_dependency_graph
    ADD CONSTRAINT fk_to_phase_phase FOREIGN KEY (to_course_phase_id) REFERENCES public.course_phase(id) ON DELETE CASCADE;


--
-- Name: note note_for_student_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note
    ADD CONSTRAINT note_for_student_fkey FOREIGN KEY (for_student) REFERENCES public.student(id);


--
-- Name: note_tag_relation note_tag_relation_note_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tag_relation
    ADD CONSTRAINT note_tag_relation_note_id_fkey FOREIGN KEY (note_id) REFERENCES public.note(id) ON DELETE CASCADE;


--
-- Name: note_tag_relation note_tag_relation_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tag_relation
    ADD CONSTRAINT note_tag_relation_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.note_tag(id) ON DELETE CASCADE;


--
-- Name: note_version note_version_for_note_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_version
    ADD CONSTRAINT note_version_for_note_fkey FOREIGN KEY (for_note) REFERENCES public.note(id);


--
-- Name: privacy_export_document privacy_export_document_export_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.privacy_export_document
    ADD CONSTRAINT privacy_export_document_export_id_fkey FOREIGN KEY (export_id) REFERENCES public.privacy_export(id);


--
-- Name: privacy_export privacy_export_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.privacy_export
    ADD CONSTRAINT privacy_export_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.student(id);


--
-- PostgreSQL database dump complete
--

\unrestrict uiXVLaqKXF7gSedZuy9c3H2gUqZa6VyxWQoZSShJpDmfp6Ju8Xhj14PSv45Sbb5

