// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeveloperProfile struct {
	CoursePhaseID         uuid.UUID   `json:"course_phase_id"`
	CourseParticipationID uuid.UUID   `json:"course_participation_id"`
	GitlabUsername        string      `json:"gitlab_username"`
	AppleID               string      `json:"apple_id"`
	HasMacbook            bool        `json:"has_macbook"`
	IphoneUuid            pgtype.UUID `json:"iphone_uuid"`
	IpadUuid              pgtype.UUID `json:"ipad_uuid"`
	AppleWatchUuid        pgtype.UUID `json:"apple_watch_uuid"`
}

type Tutor struct {
	CoursePhaseID       uuid.UUID `json:"course_phase_id"`
	ID                  uuid.UUID `json:"id"`
	FirstName           string    `json:"first_name"`
	LastName            string    `json:"last_name"`
	Email               string    `json:"email"`
	MatriculationNumber string    `json:"matriculation_number"`
	UniversityLogin     string    `json:"university_login"`
}
