// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeveloperProfile struct {
	CoursePhaseID         uuid.UUID   `json:"course_phase_id"`
	CourseParticipationID uuid.UUID   `json:"course_participation_id"`
	GitlabUsername        string      `json:"gitlab_username"`
	AppleID               string      `json:"apple_id"`
	HasMacbook            bool        `json:"has_macbook"`
	IphoneUdid            pgtype.Text `json:"iphone_udid"`
	IpadUdid              pgtype.Text `json:"ipad_udid"`
	AppleWatchUdid        pgtype.Text `json:"apple_watch_udid"`
}

type Seat struct {
	CoursePhaseID   uuid.UUID   `json:"course_phase_id"`
	SeatName        string      `json:"seat_name"`
	HasMac          bool        `json:"has_mac"`
	DeviceID        pgtype.Text `json:"device_id"`
	AssignedStudent pgtype.UUID `json:"assigned_student"`
	AssignedTutor   pgtype.UUID `json:"assigned_tutor"`
}

type StudentGitlabProcess struct {
	CoursePhaseID         uuid.UUID        `json:"course_phase_id"`
	CourseParticipationID uuid.UUID        `json:"course_participation_id"`
	GitlabSuccess         bool             `json:"gitlab_success"`
	ErrorMessage          pgtype.Text      `json:"error_message"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Tutor struct {
	CoursePhaseID       uuid.UUID   `json:"course_phase_id"`
	ID                  uuid.UUID   `json:"id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	Email               string      `json:"email"`
	MatriculationNumber string      `json:"matriculation_number"`
	UniversityLogin     string      `json:"university_login"`
	GitlabUsername      pgtype.Text `json:"gitlab_username"`
}
