// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: test.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const test = `-- name: Test :many
SELECT id from test
`

func (q *Queries) Test(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, test)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
