// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gitlab.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGitlabError = `-- name: AddGitlabError :exec
INSERT INTO student_gitlab_processes (course_phase_id, course_participation_id, gitlab_success, error_message)
VALUES ($1, $2, false, $3)
ON CONFLICT (course_phase_id, course_participation_id)
DO UPDATE SET 
    gitlab_success = EXCLUDED.gitlab_success,
    error_message = EXCLUDED.error_message,
    updated_at = CURRENT_TIMESTAMP
`

type AddGitlabErrorParams struct {
	CoursePhaseID         uuid.UUID   `json:"course_phase_id"`
	CourseParticipationID uuid.UUID   `json:"course_participation_id"`
	ErrorMessage          pgtype.Text `json:"error_message"`
}

func (q *Queries) AddGitlabError(ctx context.Context, arg AddGitlabErrorParams) error {
	_, err := q.db.Exec(ctx, addGitlabError, arg.CoursePhaseID, arg.CourseParticipationID, arg.ErrorMessage)
	return err
}

const addGitlabStatus = `-- name: AddGitlabStatus :exec
INSERT INTO student_gitlab_processes (course_phase_id, course_participation_id, gitlab_success)
VALUES ($1, $2, true)
ON CONFLICT (course_phase_id, course_participation_id)
DO UPDATE SET 
    gitlab_success = EXCLUDED.gitlab_success,
    updated_at = CURRENT_TIMESTAMP,
    error_message = NULL
`

type AddGitlabStatusParams struct {
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
}

func (q *Queries) AddGitlabStatus(ctx context.Context, arg AddGitlabStatusParams) error {
	_, err := q.db.Exec(ctx, addGitlabStatus, arg.CoursePhaseID, arg.CourseParticipationID)
	return err
}

const createTutorGitlabSubgroup = `-- name: CreateTutorGitlabSubgroup :exec
INSERT INTO tutor_gitlab_subgroup (course_phase_id, tutor_id, gitlab_group_id, gitlab_group_path)
VALUES ($1, $2, $3, $4)
ON CONFLICT (course_phase_id, tutor_id) DO NOTHING
`

type CreateTutorGitlabSubgroupParams struct {
	CoursePhaseID   uuid.UUID `json:"course_phase_id"`
	TutorID         uuid.UUID `json:"tutor_id"`
	GitlabGroupID   int64     `json:"gitlab_group_id"`
	GitlabGroupPath string    `json:"gitlab_group_path"`
}

func (q *Queries) CreateTutorGitlabSubgroup(ctx context.Context, arg CreateTutorGitlabSubgroupParams) error {
	_, err := q.db.Exec(ctx, createTutorGitlabSubgroup,
		arg.CoursePhaseID,
		arg.TutorID,
		arg.GitlabGroupID,
		arg.GitlabGroupPath,
	)
	return err
}

const getAllGitlabStatus = `-- name: GetAllGitlabStatus :many
SELECT course_phase_id, course_participation_id, gitlab_success, error_message, created_at, updated_at FROM student_gitlab_processes WHERE course_phase_id = $1
`

func (q *Queries) GetAllGitlabStatus(ctx context.Context, coursePhaseID uuid.UUID) ([]StudentGitlabProcess, error) {
	rows, err := q.db.Query(ctx, getAllGitlabStatus, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentGitlabProcess
	for rows.Next() {
		var i StudentGitlabProcess
		if err := rows.Scan(
			&i.CoursePhaseID,
			&i.CourseParticipationID,
			&i.GitlabSuccess,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTutorGitlabSubgroup = `-- name: GetTutorGitlabSubgroup :one
SELECT gitlab_group_id, gitlab_group_path
FROM tutor_gitlab_subgroup
WHERE course_phase_id = $1
  AND tutor_id = $2
`

type GetTutorGitlabSubgroupParams struct {
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
	TutorID       uuid.UUID `json:"tutor_id"`
}

type GetTutorGitlabSubgroupRow struct {
	GitlabGroupID   int64  `json:"gitlab_group_id"`
	GitlabGroupPath string `json:"gitlab_group_path"`
}

func (q *Queries) GetTutorGitlabSubgroup(ctx context.Context, arg GetTutorGitlabSubgroupParams) (GetTutorGitlabSubgroupRow, error) {
	row := q.db.QueryRow(ctx, getTutorGitlabSubgroup, arg.CoursePhaseID, arg.TutorID)
	var i GetTutorGitlabSubgroupRow
	err := row.Scan(&i.GitlabGroupID, &i.GitlabGroupPath)
	return i, err
}
