// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: peerAssignment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPeerAssignment = `-- name: CreatePeerAssignment :exec
INSERT INTO peer_assignment (course_phase_id, student_id, peer_id)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT peer_assignment_pkey DO NOTHING
`

type CreatePeerAssignmentParams struct {
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
	StudentID     uuid.UUID `json:"student_id"`
	PeerID        uuid.UUID `json:"peer_id"`
}

func (q *Queries) CreatePeerAssignment(ctx context.Context, arg CreatePeerAssignmentParams) error {
	_, err := q.db.Exec(ctx, createPeerAssignment, arg.CoursePhaseID, arg.StudentID, arg.PeerID)
	return err
}

const deletePeerAssignments = `-- name: DeletePeerAssignments :exec
DELETE FROM peer_assignment
WHERE course_phase_id = $1
`

func (q *Queries) DeletePeerAssignments(ctx context.Context, coursePhaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePeerAssignments, coursePhaseID)
	return err
}

const getPeerAssignments = `-- name: GetPeerAssignments :many
SELECT course_phase_id, student_id, peer_id FROM peer_assignment
WHERE course_phase_id = $1
`

func (q *Queries) GetPeerAssignments(ctx context.Context, coursePhaseID uuid.UUID) ([]PeerAssignment, error) {
	rows, err := q.db.Query(ctx, getPeerAssignments, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeerAssignment
	for rows.Next() {
		var i PeerAssignment
		if err := rows.Scan(&i.CoursePhaseID, &i.StudentID, &i.PeerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeersForStudent = `-- name: GetPeersForStudent :many
SELECT pa.peer_id, dp.gitlab_username, s.seat_name,
       t.gitlab_username AS tutor_gitlab_username
FROM peer_assignment pa
LEFT JOIN developer_profile dp
  ON pa.course_phase_id = dp.course_phase_id
  AND pa.peer_id = dp.course_participation_id
LEFT JOIN seat s
  ON pa.course_phase_id = s.course_phase_id
  AND pa.peer_id = s.assigned_student
LEFT JOIN tutor t
  ON s.course_phase_id = t.course_phase_id
  AND s.assigned_tutor = t.id
WHERE pa.course_phase_id = $1
  AND pa.student_id = $2
`

type GetPeersForStudentParams struct {
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
	StudentID     uuid.UUID `json:"student_id"`
}

type GetPeersForStudentRow struct {
	PeerID              uuid.UUID   `json:"peer_id"`
	GitlabUsername      pgtype.Text `json:"gitlab_username"`
	SeatName            pgtype.Text `json:"seat_name"`
	TutorGitlabUsername pgtype.Text `json:"tutor_gitlab_username"`
}

func (q *Queries) GetPeersForStudent(ctx context.Context, arg GetPeersForStudentParams) ([]GetPeersForStudentRow, error) {
	rows, err := q.db.Query(ctx, getPeersForStudent, arg.CoursePhaseID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPeersForStudentRow
	for rows.Next() {
		var i GetPeersForStudentRow
		if err := rows.Scan(
			&i.PeerID,
			&i.GitlabUsername,
			&i.SeatName,
			&i.TutorGitlabUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewersForStudent = `-- name: GetReviewersForStudent :many
SELECT pa.student_id, dp.gitlab_username, s.seat_name,
       t.gitlab_username AS tutor_gitlab_username
FROM peer_assignment pa
LEFT JOIN developer_profile dp
  ON pa.course_phase_id = dp.course_phase_id
  AND pa.student_id = dp.course_participation_id
LEFT JOIN seat s
  ON pa.course_phase_id = s.course_phase_id
  AND pa.student_id = s.assigned_student
LEFT JOIN tutor t
  ON s.course_phase_id = t.course_phase_id
  AND s.assigned_tutor = t.id
WHERE pa.course_phase_id = $1
  AND pa.peer_id = $2
`

type GetReviewersForStudentParams struct {
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
	PeerID        uuid.UUID `json:"peer_id"`
}

type GetReviewersForStudentRow struct {
	StudentID           uuid.UUID   `json:"student_id"`
	GitlabUsername      pgtype.Text `json:"gitlab_username"`
	SeatName            pgtype.Text `json:"seat_name"`
	TutorGitlabUsername pgtype.Text `json:"tutor_gitlab_username"`
}

func (q *Queries) GetReviewersForStudent(ctx context.Context, arg GetReviewersForStudentParams) ([]GetReviewersForStudentRow, error) {
	rows, err := q.db.Query(ctx, getReviewersForStudent, arg.CoursePhaseID, arg.PeerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewersForStudentRow
	for rows.Next() {
		var i GetReviewersForStudentRow
		if err := rows.Scan(
			&i.StudentID,
			&i.GitlabUsername,
			&i.SeatName,
			&i.TutorGitlabUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
