// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTeamAllocation = `-- name: GetTeamAllocation :one
SELECT t.id AS team_id
FROM seat s
         JOIN tutor t
              ON t.course_phase_id = s.course_phase_id
                  AND t.id = s.assigned_tutor
WHERE s.course_phase_id = $1
  AND s.assigned_student = $2::uuid
ORDER BY s.seat_name
LIMIT 1
`

type GetTeamAllocationParams struct {
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
}

func (q *Queries) GetTeamAllocation(ctx context.Context, arg GetTeamAllocationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTeamAllocation, arg.CoursePhaseID, arg.CourseParticipationID)
	var team_id uuid.UUID
	err := row.Scan(&team_id)
	return team_id, err
}

const getTeamAllocations = `-- name: GetTeamAllocations :many
SELECT DISTINCT ON (s.assigned_student) s.assigned_student::uuid AS course_participation_id,
                                        t.id                     AS team_id
FROM seat s
         JOIN tutor t
              ON t.course_phase_id = s.course_phase_id
                  AND t.id = s.assigned_tutor
WHERE s.course_phase_id = $1
  AND s.assigned_student IS NOT NULL
ORDER BY s.assigned_student, s.seat_name
`

type GetTeamAllocationsRow struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	TeamID                uuid.UUID `json:"team_id"`
}

// A student seated twice counts for the first seat by name, matching GetTeamAllocation.
func (q *Queries) GetTeamAllocations(ctx context.Context, coursePhaseID uuid.UUID) ([]GetTeamAllocationsRow, error) {
	rows, err := q.db.Query(ctx, getTeamAllocations, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamAllocationsRow
	for rows.Next() {
		var i GetTeamAllocationsRow
		if err := rows.Scan(&i.CourseParticipationID, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTutorTeams = `-- name: GetTutorTeams :many
SELECT t.id,
       t.first_name,
       t.last_name,
       COALESCE(members.team_members, '[]'::jsonb)::jsonb AS team_members
FROM tutor t
         LEFT JOIN LATERAL (
    SELECT jsonb_agg(
                   jsonb_build_object(
                           'id', s.assigned_student,
                           'firstName', COALESCE(pn.first_name, ''),
                           'lastName', COALESCE(pn.last_name, '')
                   )
                   ORDER BY pn.first_name, pn.last_name, s.seat_name
           ) AS team_members
    FROM seat s
             LEFT JOIN participant_name pn
                       ON pn.course_phase_id = s.course_phase_id
                           AND pn.course_participation_id = s.assigned_student
    WHERE s.course_phase_id = t.course_phase_id
      AND s.assigned_tutor = t.id
      AND s.assigned_student IS NOT NULL
    ) members ON TRUE
WHERE t.course_phase_id = $1
ORDER BY t.first_name, t.last_name
`

type GetTutorTeamsRow struct {
	ID          uuid.UUID `json:"id"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	TeamMembers []byte    `json:"team_members"`
}

// One team per tutor: the tutor plus every student seated in one of their seats.
func (q *Queries) GetTutorTeams(ctx context.Context, coursePhaseID uuid.UUID) ([]GetTutorTeamsRow, error) {
	rows, err := q.db.Query(ctx, getTutorTeams, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTutorTeamsRow
	for rows.Next() {
		var i GetTutorTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.TeamMembers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertParticipantNames = `-- name: UpsertParticipantNames :exec
INSERT INTO participant_name (course_phase_id, course_participation_id, first_name, last_name)
SELECT $1::uuid,
       unnest($2::uuid[]),
       unnest($3::text[]),
       unnest($4::text[])
ON CONFLICT (course_phase_id, course_participation_id) DO UPDATE
    SET first_name = EXCLUDED.first_name,
        last_name  = EXCLUDED.last_name
`

type UpsertParticipantNamesParams struct {
	CoursePhaseID          uuid.UUID   `json:"course_phase_id"`
	CourseParticipationIds []uuid.UUID `json:"course_participation_ids"`
	FirstNames             []string    `json:"first_names"`
	LastNames              []string    `json:"last_names"`
}

// The arrays are zipped by position (set-returning functions in the select list
// advance in lockstep), so callers must pass them with equal lengths.
func (q *Queries) UpsertParticipantNames(ctx context.Context, arg UpsertParticipantNamesParams) error {
	_, err := q.db.Exec(ctx, upsertParticipantNames,
		arg.CoursePhaseID,
		arg.CourseParticipationIds,
		arg.FirstNames,
		arg.LastNames,
	)
	return err
}
