// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/course_phase/{coursePhaseID}/developer_profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns all developer profiles for the course phase.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "developer-profile"
                ],
                "summary": "Get all developer profiles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/developerProfileDTO.DeveloperProfile"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a developer profile for the authenticated student.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "developer-profile"
                ],
                "summary": "Create developer profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Developer profile payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/developerProfileDTO.PostDeveloperProfile"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/developer_profile/self": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the developer profile for the authenticated student.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "developer-profile"
                ],
                "summary": "Get own developer profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/developerProfileDTO.DeveloperProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/developer_profile/{courseParticipationID}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates or updates a developer profile for a course participation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "developer-profile"
                ],
                "summary": "Update developer profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course Participation UUID",
                        "name": "courseParticipationID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Developer profile payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/developerProfileDTO.DeveloperProfile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/devices": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the device list for each course participation in the course phase.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Get devices for all participations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/developerProfileDTO.DeviceWithParticipationID"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/devices/{courseParticipationID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns device identifiers for the specified course participation.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Get devices for course participation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course Participation UUID",
                        "name": "courseParticipationID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/infrastructure/gitlab/course-setup": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates the GitLab course infrastructure for the course phase.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "infrastructure"
                ],
                "summary": "Create course infrastructure",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Course infrastructure request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/infrastructureDTO.CreateCourseInfrastructureRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/infrastructure/gitlab/student-setup": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns GitLab setup status for all course participations.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "infrastructure"
                ],
                "summary": "Get student GitLab status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/infrastructureDTO.GitlabStatus"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/infrastructure/gitlab/student-setup/{courseParticipationID}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates the GitLab repository for a student.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "infrastructure"
                ],
                "summary": "Create student infrastructure",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course Participation UUID",
                        "name": "courseParticipationID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Student repository request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/infrastructureDTO.CreateStudentRepo"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/infrastructure/gitlab/student-setup/{courseParticipationID}/manual": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Marks GitLab setup as completed for a student.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "infrastructure"
                ],
                "summary": "Manually overwrite student GitLab status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course Participation UUID",
                        "name": "courseParticipationID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/seat_plan": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the seat plan for the course phase.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seat-plan"
                ],
                "summary": "Get seat plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/seatPlanDTO.Seat"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Updates the seat plan assignments and device information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seat-plan"
                ],
                "summary": "Update seat plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Seat plan updates",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/seatPlanDTO.Seat"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates the initial seat plan with seat names.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seat-plan"
                ],
                "summary": "Create seat plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Seat names",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes the seat plan for the course phase.",
                "tags": [
                    "seat-plan"
                ],
                "summary": "Delete seat plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/seat_plan/own-assignment": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the seat assignment for the authenticated student.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seat-plan"
                ],
                "summary": "Get own seat assignment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/seatPlanDTO.SeatAssignment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/tutor": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns all tutors for the course phase.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tutor"
                ],
                "summary": "Get tutors",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tutorDTO.Tutor"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/tutor/course/{courseID}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Imports tutors and assigns them to the Keycloak groups.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tutor"
                ],
                "summary": "Import tutors",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course UUID",
                        "name": "courseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "List of tutors to import",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tutorDTO.Tutor"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/course_phase/{coursePhaseID}/tutor/{tutorID}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Updates the GitLab username for a tutor.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tutor"
                ],
                "summary": "Update tutor GitLab username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course Phase UUID",
                        "name": "coursePhaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tutor UUID",
                        "name": "tutorID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "GitLab username update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tutorDTO.UpdateTutor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "developerProfileDTO.DeveloperProfile": {
            "type": "object",
            "properties": {
                "appleID": {
                    "type": "string"
                },
                "appleWatchUDID": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "courseParticipationID": {
                    "type": "string"
                },
                "coursePhaseID": {
                    "type": "string"
                },
                "gitLabUsername": {
                    "type": "string"
                },
                "hasMacBook": {
                    "type": "boolean"
                },
                "iPadUDID": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "iPhoneUDID": {
                    "$ref": "#/definitions/pgtype.Text"
                }
            }
        },
        "developerProfileDTO.DeviceWithParticipationID": {
            "type": "object",
            "properties": {
                "courseParticipationID": {
                    "type": "string"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "developerProfileDTO.PostDeveloperProfile": {
            "type": "object",
            "properties": {
                "appleID": {
                    "type": "string"
                },
                "appleWatchUDID": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "gitLabUsername": {
                    "type": "string"
                },
                "hasMacBook": {
                    "type": "boolean"
                },
                "iPadUDID": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "iPhoneUDID": {
                    "$ref": "#/definitions/pgtype.Text"
                }
            }
        },
        "infrastructureDTO.CreateCourseInfrastructureRequest": {
            "type": "object",
            "properties": {
                "semesterTag": {
                    "type": "string"
                }
            }
        },
        "infrastructureDTO.CreateStudentRepo": {
            "type": "object",
            "properties": {
                "repoName": {
                    "type": "string"
                },
                "semesterTag": {
                    "type": "string"
                },
                "studentName": {
                    "type": "string"
                },
                "submissionDeadline": {
                    "type": "string"
                }
            }
        },
        "infrastructureDTO.GitlabStatus": {
            "type": "object",
            "properties": {
                "courseParticipationID": {
                    "type": "string"
                },
                "coursePhaseID": {
                    "type": "string"
                },
                "createdAt": {
                    "$ref": "#/definitions/pgtype.Timestamp"
                },
                "errorMessage": {
                    "type": "string"
                },
                "gitlabSuccess": {
                    "type": "boolean"
                },
                "updatedAt": {
                    "$ref": "#/definitions/pgtype.Timestamp"
                }
            }
        },
        "pgtype.InfinityModifier": {
            "type": "integer",
            "format": "int32",
            "enum": [
                1,
                0,
                -1
            ],
            "x-enum-varnames": [
                "Infinity",
                "Finite",
                "NegativeInfinity"
            ]
        },
        "pgtype.Text": {
            "type": "object",
            "properties": {
                "string": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "pgtype.Timestamp": {
            "type": "object",
            "properties": {
                "infinityModifier": {
                    "$ref": "#/definitions/pgtype.InfinityModifier"
                },
                "time": {
                    "description": "Time zone will be ignored when encoding to PostgreSQL.",
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "seatPlanDTO.Seat": {
            "type": "object",
            "properties": {
                "assignedStudent": {
                    "description": "using pgtype bc. it might be empty",
                    "type": "string"
                },
                "assignedTutor": {
                    "type": "string"
                },
                "deviceID": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "hasMac": {
                    "type": "boolean"
                },
                "seatName": {
                    "type": "string"
                }
            }
        },
        "seatPlanDTO.SeatAssignment": {
            "type": "object",
            "properties": {
                "deviceID": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "hasMac": {
                    "type": "boolean"
                },
                "seatName": {
                    "type": "string"
                },
                "studentCourseParticipationID": {
                    "type": "string"
                },
                "tutorEmail": {
                    "type": "string"
                },
                "tutorFirstName": {
                    "type": "string"
                },
                "tutorLastName": {
                    "type": "string"
                }
            }
        },
        "tutorDTO.Tutor": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gitlabUsername": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "matriculationNumber": {
                    "type": "string"
                },
                "universityLogin": {
                    "type": "string"
                }
            }
        },
        "tutorDTO.UpdateTutor": {
            "type": "object",
            "properties": {
                "gitlabUsername": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Bearer token authentication. Use format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "PROMPT Documentation",
        "url": "https://ls1intum.github.io/prompt2/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/intro-course/api",
	Schemes:          []string{},
	Title:            "PROMPT Intro Course API",
	Description:      "This is the intro course server of PROMPT.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
