name: Deploy Intro Course

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      server_image_tag:
        required: true
        type: string
      client_image_tag:
        required: true
        type: string
    secrets:
      VM_SSH_PRIVATE_KEY:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: "https://${{ vars.CORE_HOST }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Copy compose file to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
          proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
          source: "docker-compose.prod.yml"
          target: "/home/${{ vars.VM_USERNAME }}/prompt-intro-course/"

      - name: Deploy intro course containers
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
          proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
          script: |
            mkdir -p /home/${{ vars.VM_USERNAME }}/prompt-intro-course
            cd /home/${{ vars.VM_USERNAME }}/prompt-intro-course

            cat > .env.prod <<EOT
            CORE_HOST=${{ vars.CORE_HOST }}
            SERVER_CORE_HOST=${{ vars.SERVER_CORE_HOST }}
            SERVER_IMAGE_TAG=${{ inputs.server_image_tag }}
            CLIENT_IMAGE_TAG=${{ inputs.client_image_tag }}
            DB_NAME=${{ vars.DB_NAME }}
            DB_USER=${{ vars.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            KEYCLOAK_HOST=${{ vars.KEYCLOAK_HOST }}
            KEYCLOAK_REALM_NAME=${{ vars.KEYCLOAK_REALM_NAME }}
            KEYCLOAK_AUTHORIZED_PARTY=${{ vars.KEYCLOAK_AUTHORIZED_PARTY }}
            KEYCLOAK_CLIENT_ID=${{ vars.KEYCLOAK_CLIENT_ID }}
            GITLAB_ACCESS_TOKEN=${{ vars.GITLAB_ACCESS_TOKEN }}
            SENTRY_DSN=${{ vars.SENTRY_DSN || vars.SENTRY_DSN_INTRO_COURSE }}
            EOT

            docker compose -f docker-compose.prod.yml --env-file=.env.prod up --pull=always -d
