name: Lint Client

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: "20.20.2"
          cache: "yarn"
          cache-dependency-path: ./client/yarn.lock
      - run: yarn install
      - name: Run client lint
        run: yarn lint
