name: Vet Server

on:
  workflow_call:

permissions:
  contents: read

jobs:
  vet-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache-dependency-path: "server/go.sum"
      - name: Install dependencies
        run: |
          cd server
          go mod download
      - name: go vet
        run: |
          cd server
          go vet ./...
